// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzblvzcvklsgaqewgtlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6Ymx2emN2a2xzZ2FxZXdndGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDYxMDEsImV4cCI6MjA2NTQ4MjEwMX0.fALG7nW92mlE77nhH_6bPTJEaYJWcJSqtO1poeH0d08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});